
branches:
  only:
    - master

language: minimal

sudo: true

cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.cache/sccache/
    - $TRAVIS_HOME/.rustup/
    - $TRAVIS_HOME/.nvm/
    - node/target
    - dns_utility/target
    - node-ui/node_modules
    - node-ui/dist/

script: echo "Nothing"

jobs:
  include:
    - stage: "Install Toolchains"
      script: |
          ci/install_node_toolchain.sh
          ci/install_ui_toolchain.sh

    - stage: "Build Binaries and Run Quick Tests"
      env:
        - NODE_JS_VERSION=10.6.3 RUSTC_WRAPPER=sccache
      before_script: |
        ci/prepare_build.sh
        node/ci/build.sh
        dns_utility/ci/build.sh
      script:
        - node/ci/unit_tests.sh
        - dns_utility/ci/unit_tests.sh
        - node/ci/integration_tests.sh && dns_utility/ci/integration_tests.sh
        - node-ui/unit_tests.sh
        - node-ui/ci/build.sh

    - stage: "Run Slow Tests"
      env:
        - NODE_JS_VERSION=10.6.3 RUSTC_WRAPPER=sccache
      before_script: |
        ci/sccache.sh
      script:
        - node-ui/ci/ng_tests.sh
        - xvfb-run -a -e /tmp/xvfb.out -s "-screen 0 1024x768x8" node-ui/ci/integration_tests.sh
        - multinode_integration_tests/ci/all.sh
