
branches:
  only:
    - master

script: echo "Nothing here..."

jobs:
  include:
    - stage: "Stage 1"
    - sudo: true
    - env:
        - NODE_JS_VERSION="10.6.3" PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
    - cache:
      - directories:
        - $TRAVIS_HOME/.cargo/
        - $TRAVIS_HOME/.cache/sccache/
        - $TRAVIS_HOME/.rustup/
        - $TRAVIS_HOME/.nvm/
        - node/target
        - dns_utility/target
        - port_exposer
        - node-ui/node_modules
        - node-ui/dist/
    - install:
      - |
        ci/install_node_toolchain.sh &&
        ci/install_ui_toolchain.sh
    - before_script:
      - |
        ci/prepare_build.sh &&
        node/ci/build.sh &&
        dns_utility/ci/build.sh
    - script:
      - node/ci/unit_tests.sh
      - dns_utility/ci/unit_tests.sh
      - node/ci/integration_tests.sh && dns_utility/ci/integration_tests.sh
      - node-ui/ci/unit_tests.sh
      - node-ui/ci/build.sh

    - stage: "Stage 2"
    - cache:
      - directories:
        - $TRAVIS_HOME/.cargo/
        - $TRAVIS_HOME/.cache/sccache/
        - $TRAVIS_HOME/.rustup/
        - $TRAVIS_HOME/.nvm/
        - node/target
        - dns_utility/target
        - port_exposer
        - node-ui/node_modules
        - node-ui/dist/
    - env:
        - NODE_JS_VERSION="10.6.3" PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
    - install:
        - |
          ci/install_node_toolchain.sh &&
          ci/install_ui_toolchain.sh
    - before_script:
      - ci/sccache.sh
    - script:
      - node-ui/ci/ng_tests.sh
      - xvfb-run -a -e /tmp/xvfb.out -s "-screen 0 1024x768x8" node-ui/ci/integration_tests.sh
      - multinode_integration_tests/ci/all.sh
