
branches:
  only:
    - master

language: rust
rust:
  - stable

sudo: true

env:
  - NODE_JS_VERSION=10.6.3

cache:
  directories:
    - $HOME/.cargo/registry
    - $HOME/.cache/sccache
    - node/target/release/build
    - node/target/release/deps
    - node/target/release/examples
    - node/target/release/incremental
    - node/target/release/native
    - dns_utility/target/release/build
    - dns_utility/target/release/deps
    - dns_utility/target/release/examples
    - dns_utility/target/release/incremental
    - dns_utility/target/release/native
    - port_exposer
    - node-ui/node_modules

before_install:
  - |
    curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
    sudo apt-get install -y nodejs
    nvm install 10.16.3
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update && sudo apt-get install -y yarn xvfb

install:
  - rustup component add rustfmt
#  - rustup component add clippy # Not using this in Travis CI

jobs:
  include:
    - stage: "Stage 0"
    - script: ci/prepare_build.sh
      name: "Prepare Build"

    - stage: "Stage 1"
    - script: node/ci/build.sh
      name: "Build SubstratumNode"
    - script: dns_utility/ci/build.sh
      name: "Build dns_utility"
    - script: node-ui/ci/unit_tests.sh
      name: "Node UI Unit Tests"

    - stage: "Stage 2"
    - script: node/ci/unit_tests.sh
      name: "SubstratumNode Unit Tests"
    - script: node/ci/integration_tests.sh
      name: "SubstratumNode Zero-Hop Integration Tests"
    - script: dns_utility/ci/unit_tests.sh
      name: "dns_utility Unit Tests"
    - script: dns_utility/ci/integration_tests.sh
      name: "dns_utility Integration Tests"
    - script: multinode_integration_tests/ci/all.sh
      name: "Multinode Integration Tests"
    - script: node-ui/ci/build.sh
      name: "Node UI Build"

    - stage: "Stage 3"
    - script: node-ui/ci/ng_tests.sh
      name: "Node UI Angular Tests"
    - script: xvfb-run -a -e /tmp/xvfb.out -s "-screen 0 1024x768x8" node-ui/ci/integration_tests.sh
      name: "Node UI Integration Tests"
