
branches:
  only:
    - master

language: minimal

sudo: true

cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.rustup/
    - $TRAVIS_HOME/.nvm/
    - $TRAVIS_HOME/.cache/sccache/
    - node/target
    - dns_utility/target
    - node-ui/node_modules

os: linux

jobs:
  include:
    - stage: "Install Toolchains"
      workspaces:
        create:
          name: toolchains
          paths:
            - $TRAVIS_HOME/.cargo/
            - $TRAVIS_HOME/.rustup/
            - $TRAVIS_HOME/.nvm/
            - $TRAVIS_HOME/.cache/sccache/
      script: |
        ci/install_node_toolchain.sh
        ci/install_ui_toolchain.sh

    - stage: "Build Binaries"
      env:
        - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      name: "Build SubstratumNode"
      workspaces:
        use: toolchains
        create:
          name: node_binaries
          paths:
            - $TRAVIS_HOME/.cache/sccache/
            - node/target
      before_script: |
        ci/sccache.sh
      script: |
        ci/prepare_node_build.sh
        node/ci/build.sh
    - env:
        - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      name: "Build dns_utility"
      workspaces:
        use: toolchains
        create:
          name: dns_utility_binaries
          paths:
            - $TRAVIS_HOME/.cache/sccache/
            - dns_utility/target
      before_script: |
        ci/sccache.sh
      script: |
        dns_utility/ci/build.sh

    - stage: "Run Quick Tests"
      env:
        - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
      name: "Run node-ui Unit Tests"
      workspaces:
        use:
          - toolchains
          - binaries
        create:
          name: node_ui_generated
          paths:
            - node-ui/generated
      script: |
        nvm use $NODE_JS_VERSION
        node-ui/ci/unit_tests.sh
      after_failure: |
        ci/collect_results.sh
        ci/publish_results.sh Failure
    - env:
        - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      name: "Transpile node-ui TypeScript"
      workspaces:
        use:
          - toolchains
          - node_binaries
          - dns_utility_binaries
        create:
          name: node_ui_binaries
          paths:
            - node-ui/node_modules
            - node-ui/dist/
      script: |
        nvm use $NODE_JS_VERSION
        ci/prepare_node_ui_build.sh
        node-ui/ci/build.sh
      after_failure: |
        ci/collect_results.sh
        ci/publish_results.sh Failure
    - env:
        - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      name: "Run SubstratumNode Unit Tests"
      workspaces:
        use:
          - toolchains
          - node_binaries
        create:
          name: node_generated
          paths:
            - node/generated
      before_script: |
        ci/sccache.sh
      script: |
        node/ci/unit_tests.sh
      after_failure: |
        ci/collect_results.sh
        ci/publish_results.sh Failure
    - env:
        - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      name: "Run dns_utility Unit Tests"
      workspaces:
        use:
          - toolchains
          - dns_utility_binaries
        create:
          name: dns_utility_generated
          paths:
            - dns_utility/generated
      before_script: |
        ci/sccache.sh
      script: |
        dns_utility/ci/unit_tests.sh
      after_failure: |
        ci/collect_results.sh
        ci/publish_results.sh Failure
    - env:
        - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      name: "Run SubstratumNode and dns_utility Zero-Hop Integration Tests"
      workspaces:
        use:
          - toolchains
          - node_binaries
          - dns_utility_binaries
      before_script: |
        ci/sccache.sh
      script: |
        node/ci/integration_tests.sh && dns_utility/ci/integration_tests.sh
      after_failure: |
        ci/collect_results.sh
        ci/publish_results.sh Failure

    - stage: "Run Slow Tests"
      env:
        - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
      name: "Run node-ui Angular Tests"
      workspaces:
        use:
          - toolchains
          - dns_utility_binaries
          - node_binaries
          - node_ui_binaries
          - node_generated
          - dns_utility_generated
          - node_ui_generated
      install: |
        ci/install_ui_test_toolchain.sh
      script:
        - nvm use $NODE_JS_VERSION
        - node-ui/ci/ng_tests.sh
      after_failure: |
        ci/collect_results.sh
        ci/publish_results.sh Failure
    - env:
        - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
      name: "Run node-ui Integration Tests"
      workspaces:
        use:
          - toolchains
          - dns_utility_binaries
          - node_binaries
          - node_ui_binaries
          - node_generated
          - dns_utility_generated
          - node_ui_generated
      install: |
        ci/install_ui_test_toolchain.sh
      script:
        - nvm use $NODE_JS_VERSION
        - node-ui/ci/integration_tests.sh
      after_failure: |
        ci/collect_results.sh
        ci/publish_results.sh Failure
    - env:
        - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
      name: "Run Multi-Node Integration Tests (only on Linux)"
      workspaces:
        use:
          - toolchains
          - dns_utility_binaries
          - node_binaries
          - node_generated
          - dns_utility_generated
          - node_ui_generated
      install: |
        ci/install_ui_test_toolchain.sh
      before_script: |
        ci/sccache.sh
      script:
        - ci/multinode_integration_test.sh
      after_failure: |
        ci/collect_results.sh
        ci/publish_results.sh Failure
    - stage: "Deploy"
      env:
        - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
      name: "Publish Successful Results"
      workspaces:
        use:
          - node_ui_binaries
      script: |
        ci/collect_results.sh
        ci/publish_results.sh Success
