
branches:
  only:
    - master

#language: rust
#rust:
#  - stable

sudo: true

env:
  - NODE_JS_VERSION=10.6.3

script:
  - echo "Don't try to build in this directory!"

jobs:
  include:
    - stage: "Stage 1"
    - cache:
      - directories:
        - $TRAVIS_HOME/.cargo/
        - $TRAVIS_HOME/.cache/sccache/
        - $TRAVIS_HOME/.rustup/
        - node/target
        - dns_utility/target
        - port_exposer
        - node-ui/node_modules
        - node-ui/dist/
    - before_install:
      - |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - &&
        curl -sL https://deb.nodesource.com/setup_10.x | sudo bash - ||
        sudo apt-get install -y nodejs &&
        nvm install 10.16.3 &&
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list &&
        sudo apt-get install -y yarn xvfb
    - install:
      - |
        rustup component add rustfmt &&
        rustup component add clippy
    - before_script:
      - |
        ci/prepare_build.sh &&
        node/ci/build.sh &&
        dns_utility/ci/build.sh
    - script:
      - node/ci/unit_tests.sh
      - dns_utility/ci/unit_tests.sh
      - node/ci/integration_tests.sh && dns_utility/ci/integration_tests.sh
      - node-ui/unit_tests.sh
      - node-ui/ci/build.sh

    - stage: "Stage 2"
    - cache:
      - directories:
        - $TRAVIS_HOME/.cargo/
        - $TRAVIS_HOME/.cache/sccache/
        - $TRAVIS_HOME/.rustup/
        - node/target
        - dns_utility/target
        - port_exposer
        - node-ui/node_modules
        - node-ui/dist/
    - before_script:
      - ci/sccache.sh
    - script:
      - node-ui/ci/ng_tests.sh
      - xvfb-run -a -e /tmp/xvfb.out -s "-screen 0 1024x768x8" node-ui/ci/integration_tests.sh
      - multinode_integration_tests/ci/all.sh
