
branches:
  only:
    - master

language: minimal

sudo: true

cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.rustup/
    - $TRAVIS_HOME/.nvm/
    - $TRAVIS_HOME/.cache/sccache/
    - node/target
    - dns_utility/target
    - node-ui/node_modules

script: echo "Nothing"

jobs:
  include:
    - stage: "Install Toolchains"
      workspaces:
        create:
          name: toolchains
          paths:
            - $TRAVIS_HOME/.cargo/
            - $TRAVIS_HOME/.rustup/
            - $TRAVIS_HOME/.nvm/
      script: |
          ci/install_node_toolchain.sh
          ci/install_ui_toolchain.sh

    - stage: "Build Binaries"
      env:
        - NODE_JS_VERSION=10.6.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      workspaces:
        use: toolchains
        create:
          name: binaries
          paths:
            - $TRAVIS_HOME/.cache/sccache/
            - node/target
            - dns_utility/target
            - node-ui/node_modules
            - node-ui/dist/
      script: |
        echo "Path: $PATH"
        ls -lR "$TRAVIS_HOME/.cargo/bin"
        ci/prepare_build.sh
        node/ci/build.sh
        dns_utility/ci/build.sh

    - stage: "Run Quick Tests"
      env:
        - NODE_JS_VERSION=10.6.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      workspaces:
        use:
          - toolchains
          - binaries
#      before_script: |
#        ci/sccache.sh
      script:
        - node/ci/unit_tests.sh
        - dns_utility/ci/unit_tests.sh
        - node/ci/integration_tests.sh && dns_utility/ci/integration_tests.sh
        - node-ui/unit_tests.sh
        - node-ui/ci/build.sh

    - stage: "Run Slow Tests"
      env:
        - NODE_JS_VERSION=10.6.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
      workspaces:
        use:
          - toolchains
          - binaries
#      before_script: |
#        ci/sccache.sh
      script:
        - node-ui/ci/ng_tests.sh
        - xvfb-run -a -e /tmp/xvfb.out -s "-screen 0 1024x768x8" node-ui/ci/integration_tests.sh
        - multinode_integration_tests/ci/all.sh
