
##
## Global configuration
##

branches:
  only:
    - master

language: minimal

sudo: true

cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.rustup/
    - $TRAVIS_HOME/.nvm/
    - $TRAVIS_HOME/.cache/sccache/
    - node/target
    - dns_utility/target
    - node-ui/node_modules

##
## YAML anchors for use in build matrix below
##

### INSTALL TOOLCHAINS ###

install_toolchains: &install_toolchains
  name: "Install Rust, sccache, node.js, yarn, etc."
  workspaces:
    create:
      name: toolchains
      paths:
        - $TRAVIS_HOME/.cargo/
        - $TRAVIS_HOME/.rustup/
        - $TRAVIS_HOME/.nvm/
        - $TRAVIS_HOME/.cache/sccache/
  script: |
    ci/install_node_toolchain.sh
    ci/install_ui_toolchain.sh

### BUILD BINARIES ###

build_substratum_node: &build_substratum_node
  env:
    - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
  name: "Build SubstratumNode"
  workspaces:
    use: toolchains
    create:
      name: node_binaries
      paths:
        - $TRAVIS_HOME/.cache/sccache/
        - node/target
  before_script: |
    ci/sccache.sh
  script: |
    ci/prepare_node_build.sh
    node/ci/build.sh

build_dns_utility: &build_dns_utility
  env:
    - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
  name: "Build dns_utility"
  workspaces:
    use: toolchains
    create:
      name: dns_utility_binaries
      paths:
        - $TRAVIS_HOME/.cache/sccache/
        - dns_utility/target
  before_script: |
    ci/sccache.sh
  script: |
    dns_utility/ci/build.sh

### RUN QUICK TESTS ###

run_node_ui_unit_tests: &run_node_ui_unit_tests
  env:
    - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
  name: "Run node-ui Unit Tests"
  workspaces:
    use:
      - toolchains
      - binaries
    create:
      name: node_ui_generated
      paths:
        - node-ui/generated
  script: |
    nvm use $NODE_JS_VERSION
    node-ui/ci/unit_tests.sh
  after_failure: |
    ci/collect_results.sh
    ci/publish_results.sh Failure

transpile_node_ui_typescript: &transpile_node_ui_typescript
  env:
    - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
  name: "Transpile node-ui TypeScript"
  workspaces:
    use:
      - toolchains
      - node_binaries
      - dns_utility_binaries
    create:
      name: node_ui_binaries
      paths:
        - node-ui/node_modules
        - node-ui/dist/
  script: |
    nvm use $NODE_JS_VERSION
    ci/prepare_node_ui_build.sh
    node-ui/ci/build.sh
  after_failure: |
    ci/collect_results.sh
    ci/publish_results.sh Failure

run_substratum_node_unit_tests: &run_substratum_node_unit_tests
  env:
    - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
  name: "Run SubstratumNode Unit Tests"
  workspaces:
    use:
      - toolchains
      - node_binaries
    create:
      name: node_generated
      paths:
        - node/generated
  before_script: |
    ci/sccache.sh
  script: |
    node/ci/unit_tests.sh
  after_failure: |
    ci/collect_results.sh
    ci/publish_results.sh Failure

run_dns_utility_unit_tests: &run_dns_utility_unit_tests
  env:
    - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
  name: "Run dns_utility Unit Tests"
  workspaces:
    use:
      - toolchains
      - dns_utility_binaries
    create:
      name: dns_utility_generated
      paths:
        - dns_utility/generated
  before_script: |
    ci/sccache.sh
  script: |
    dns_utility/ci/unit_tests.sh
  after_failure: |
    ci/collect_results.sh
    ci/publish_results.sh Failure

run_node_and_dns_integration_tests: &run_node_and_dns_integration_tests
  env:
    - NODE_JS_VERSION=10.16.3 PATH="$PATH:$TRAVIS_HOME/.cargo/bin"
  name: "Run SubstratumNode and dns_utility Zero-Hop Integration Tests"
  workspaces:
    use:
      - toolchains
      - node_binaries
      - dns_utility_binaries
  before_script: |
    ci/sccache.sh
  script: |
    node/ci/integration_tests.sh && dns_utility/ci/integration_tests.sh
  after_failure: |
    ci/collect_results.sh
    ci/publish_results.sh Failure

### RUN SLOW TESTS ###

run_node_ui_angular_tests: &run_node_ui_angular_tests
  env:
    - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
  name: "Run node-ui Angular Tests"
  workspaces:
    use:
      - toolchains
      - dns_utility_binaries
      - node_binaries
      - node_ui_binaries
      - node_generated
      - dns_utility_generated
      - node_ui_generated
  install: |
    ci/install_ui_test_toolchain.sh
  script:
    - nvm use $NODE_JS_VERSION
    - node-ui/ci/ng_tests.sh
  after_failure: |
    ci/collect_results.sh
    ci/publish_results.sh Failure

run_node_ui_integration_tests: &run_node_ui_integration_tests
  env:
    - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
  name: "Run node-ui Integration Tests"
  workspaces:
    use:
      - toolchains
      - dns_utility_binaries
      - node_binaries
      - node_ui_binaries
      - node_generated
      - dns_utility_generated
      - node_ui_generated
  install: |
    ci/install_ui_test_toolchain.sh
  script:
    - nvm use $NODE_JS_VERSION
    - node-ui/ci/integration_tests.sh
  after_failure: |
    ci/collect_results.sh
    ci/publish_results.sh Failure

run_multinode_integration_tests: &run_multinode_integration_tests
  env:
    - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
  name: "Run Multi-Node Integration Tests (only on Linux)"
  workspaces:
    use:
      - toolchains
      - dns_utility_binaries
      - node_binaries
      - node_generated
      - dns_utility_generated
      - node_ui_generated
  install: |
    ci/install_ui_test_toolchain.sh
  before_script: |
    ci/sccache.sh
  script:
    - ci/multinode_integration_test.sh
  after_failure: |
    ci/collect_results.sh
    ci/publish_results.sh Failure

### DEPLOY ###

publish_successful_results: &publish_successful_results
  env:
    - NODE_JS_VERSION=10.16.3 NVM_BIN="$TRAVIS_HOME/.nvm/versions/v$NODE_JS_VERSION/bin" PATH="$TRAVIS_HOME/.cargo/bin:$NVM_BIN:$PATH"
  name: "Publish Successful Results"
  workspaces:
    use:
      - node_ui_binaries
  script: |
    ci/collect_results.sh
    ci/publish_results.sh Success

##
## Build matrix
##

jobs:
  include:
    - stage: "Install Toolchains"
      os: linux
      <<: *install_toolchains
    - os: osx
      <<: *install_toolchains
#    - os: windows
#      <<: *install_toolchains

    - stage: "Build Binaries"
      os: linux
      <<: *build_substratum_node
    - os: osx
      <<: *build_substratum_node
#    - os: windows
#      <<: *build_substratum_node
    - os: linux
      <<: *build_dns_utility
    - os: osx
      <<: *build_dns_utility
#    - os: windows
#      <<: *build_dns_utility

    - stage: "Run Quick Tests"
      os: linux
      <<: *run_node_ui_unit_tests
    - os: osx
      <<: *run_node_ui_unit_tests
#    - os: windows
#      <<: *run_node_ui_unit_tests
    - os: linux
      <<: *transpile_node_ui_typescript
    - os: osx
      <<: *transpile_node_ui_typescript
#    - os: windows
#      <<: *transpile_node_ui_typescript
    - os: linux
      <<: *run_substratum_node_unit_tests
    - os: osx
      <<: *run_substratum_node_unit_tests
#    - os: windows
#      <<: *run_substratum_node_unit_tests
    - os: linux
      <<: *run_dns_utility_unit_tests
    - os: osx
      <<: *run_dns_utility_unit_tests
#    - os: windows
#      <<: *run_dns_utility_unit_tests
    - os: linux
      <<: *run_node_and_dns_integration_tests
    - os: osx
      <<: *run_node_and_dns_integration_tests
#    - os: windows
#      <<: *run_node_and_dns_integration_tests

    - stage: "Run Slow Tests"
      os: linux
      <<: *run_node_ui_angular_tests
    - os: osx
      <<: *run_node_ui_angular_tests
#    - os: windows
#      <<: *run_node_ui_angular_tests
    - os: linux
      <<: *run_node_ui_integration_tests
    - os: osx
      <<: *run_node_ui_integration_tests
#    - os: windows
#      <<: *run_node_ui_integration_tests
    - os: linux
      <<: *run_multinode_integration_tests # Linux only

    - stage: "Deploy"
      os: linux
      <<: *publish_successful_results
    - os: osx
      <<: *publish_successful_results
#    - os: windows
#      <<: *publish_successful_results
