
branches:
  only:
    - master

language: rust
rust:
  - stable

sudo: true

env:
  - NODE_JS_VERSION=10.6.3

cache:
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.cache/sccache/
    - $TRAVIS_HOME/.rustup/
    - node/target
    - dns_utility/target
    - port_exposer
    - node-ui/node_modules

before_install:
  - |
    curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
    sudo apt-get clean
    sudo apt-get update && sudo apt-get install -y nodejs
    nvm install 10.16.3
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update && sudo apt-get install -y yarn xvfb

install:
  - |
    rustup component add rustfmt
    rustup component add clippy

script:
  - echo "Don't try to build in this directory!"

jobs:
  include:
    - stage: "Stage 1"
    - cache:
      - directories:
        - node-ui/dist/
    - before_script:
      - ci/prepare_build.sh && node/ci/build.sh && dns_utility/ci/build.sh
    - script:
      - node/ci/unit_tests.sh
      - dns_utility/ci/unit_tests.sh
      - node/ci/integration_tests.sh && dns_utility/ci/integration_tests.sh
      - node-ui/unit_tests.sh
      - node-ui/ci/build.sh

    - stage: "Stage 2"
    - cache:
        - directories:
            - node-ui/dist/
    - before_script:
      - |
        which sccache || cargo install sccache || echo "Skipping sccache installation"
        sccache --start-server || echo "sccache server already running"
        export RUSTC_WRAPPER=sccache
    - script:
      - node-ui/ci/ng_tests.sh
      - xvfb-run -a -e /tmp/xvfb.out -s "-screen 0 1024x768x8" node-ui/ci/integration_tests.sh
      - multinode_integration_tests/ci/all.sh
