# Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved.

trigger:
  - booga

pr:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

variables:
  rust_version: "1.37.0"
  node_version: "10.16.3"

pool:
  vmImage: $(imageName)

steps:
  - task: CacheBeta@0
    inputs:
      key: |
        $(rust_version) | $(Agent.OS) | "v3"
      path: $(Pipeline.Workspace)/.cargo
      cacheHitVar: NODE_TOOLCHAIN_RESTORED

  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install -g yarn'

  - bash: |
      ci/install_node_toolchain.sh '$(Pipeline.Workspace)'
    condition: ne(variables.NODE_TOOLCHAIN_RESTORED, 'true')

  - bash: |
      ci/install_ui_test_toolchain.sh '$(Pipeline.Workspace)'

  - bash: |
      ci/prepare_node_build.sh
      ci/sccache.sh
      node/ci/all.sh
      ci/prepare_node_ui_build.sh
      node-ui/ci/unit_tests.sh
      node-ui/ci/build.sh
      node-ui/ci/ng_tests.sh
      node-ui/ci/integration_tests.sh
      ci/multinode_integration_test.sh
