# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

variables:
  node_version: "10.16.3"

pool:
  vmImage: $(imageName)

steps:
  - task: CacheBeta@0
    inputs:
      key: |
        "1.37.0" | $(Agent.OS) | "v2"
      path: $(Pipeline.Workspace)/.cargo
      cacheHitVar: NODE_TOOLCHAIN_RESTORED

  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install -g yarn'

  - bash: |
      ci/install_node_toolchain.sh '$(Pipeline.Workspace)'
    condition: ne(variables.NODE_TOOLCHAIN_RESTORED, 'true')

  - bash: |
      ci/install_ui_test_toolchain.sh '$(Pipeline.Workspace)'
