# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

variables:
  BOOGA: whop

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script:
        echo "Contents of BOOGA: $BOOGA"
    displayName: 'Run a one-line script'
