# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: CacheBeta@0
    inputs:
      key: 1.37.0
      path: $(Pipeline.Workspace)/.cargo
      cacheHitVar: NODE_TOOLCHAIN_CACHED

  - bash: |
    ci/install_node_toolchain.sh $(Pipeline.Workspace)
    condition: ne(variables.NODE_TOOLCHAIN_CACHED, 'true')

  - bash: |
      echo "First Job - Step 1, line 1"
      echo "First Job - Step 1, line 2"
  - bash: |
      echo "First Job - Step 2, line 1"
      echo "First Job - Step 2, line 2"
