# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: CacheBeta@0
    inputs:
      key: |
        "1.37.0" | $(Agent.OS)
      path: $(Pipeline.Workspace)/.cargo
      cacheHitVar: NODE_TOOLCHAIN_RESTORED

  - bash: |
      echo "HOME: $HOME"
      echo "USERPROFILE: $USERPROFILE"
      ci/install_node_toolchain.sh $(Pipeline.Workspace)
    condition: ne(variables.NODE_TOOLCHAIN_RESTORED, 'true')
