# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

variables:
  BOOGA: whop

stages:
  - stage: First Stage
    jobs:
      - job: First Job
        steps:
          - bash:
              - echo "First Job - Step 1, line 1"
              - echo "First Job - Step 1, line 2"
          - bash:
              - echo "First Job - Step 2, line 1"
              - echo "First Job - Step 2, line 2"
      - job: Second Job
        steps:
          - bash:
              - echo "Second Job - Step 1, line 1"
              - echo "Second Job - Step 1, line 2"
          - bash:
              - echo "Second Job - Step 2, line 1"
              - echo "Second Job - Step 2, line 2"
  - stage: Second Stage
    jobs:
      - job: First Job
        steps:
          - bash:
              - echo "First Job - Step 1, line 1"
              - echo "First Job - Step 1, line 2"
          - bash:
              - echo "First Job - Step 2, line 1"
              - echo "First Job - Step 2, line 2"
      - job: Second Job
        steps:
          - bash:
              - echo "Second Job - Step 1, line 1"
              - echo "Second Job - Step 1, line 2"
          - bash:
              - echo "Second Job - Step 2, line 1"
              - echo "Second Job - Step 2, line 2"
