# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  - master

#strategy:
#  matrix:
#    linux:
#      imageName: "ubuntu-latest"
#    mac:
#      imageName: "macOS-latest"
#    windows:
#      imageName: "windows-latest"

variables:
  imageName: "ubuntu-latest"

stages:
  - stage: first_stage
    jobs:
      - job: first_job
        pool:
          vmImage: $(imageName)
        steps:
          - bash: |
              echo "First Job - Step 1, line 1"
              echo "First Job - Step 1, line 2"
          - bash: |
              echo "First Job - Step 2, line 1"
              echo "First Job - Step 2, line 2"
      - job: second_job
        pool:
          vmImage: $(imageName)
        steps:
          - bash: |
              echo "Second Job - Step 1, line 1"
              echo "Second Job - Step 1, line 2"
          - bash: |
              echo "Second Job - Step 2, line 1"
              echo "Second Job - Step 2, line 2"

  - stage: second_stage
    jobs:
      - job: third_job
        pool:
          vmImage: $(imageName)
        steps:
          - bash: |
              echo "Third Job - Step 1, line 1"
              echo "Third Job - Step 1, line 2"
          - bash: |
              echo "Third Job - Step 2, line 1"
              echo "Third Job - Step 2, line 2"
      - job: fourth_job
        pool:
          vmImage: $(imageName)
        steps:
          - bash: |
              echo "Fourth Job - Step 1, line 1"
              echo "Fourth Job - Step 1, line 2"
          - bash: |
              echo "Fourth Job - Step 2, line 1"
              echo "Fourth Job - Step 2, line 2"
