# Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved.

pr:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

variables:
  rust_version: "1.37.0"
  node_version: "10.16.3"

pool:
  vmImage: $(imageName)

steps:
  - task: CacheBeta@0
    inputs:
      key: |
        "$(rust_version)" | $(Agent.OS) | "v3.1"
      path: $(Pipeline.Workspace)/.cargo
      cacheHitVar: NODE_TOOLCHAIN_RESTORED

  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install -g yarn'

  - bash: ci/install_node_toolchain.sh '$(Pipeline.Workspace)'
    condition: ne(variables.NODE_TOOLCHAIN_RESTORED, 'true')
    displayName: "Install Node toolchain"

  - bash: ci/install_ui_test_toolchain.sh '$(Pipeline.Workspace)'
    displayName: "Install NodeUI test toolchain"

  - bash: PATH="$(Pipeline.Workspace)/.cargo/bin:$PATH" ci/prepare_node_build.sh
    displayName: "Prepare Node build"
  - bash: PATH="$(Pipeline.Workspace)/.cargo/bin:$PATH" ci/sccache.sh && node/ci/all.sh
    displayName: "Build Node and run tests"

  - bash: ci/prepare_node_ui_build.sh
    displayName: "Prepare NodeUI build"
  - bash: node-ui/ci/build.sh && node-ui/ci/unit_tests.sh && node-ui/ci/ng_tests.sh && node-ui/ci/integration_tests.sh
    displayName: "Build NodeUI and run tests"

  - bash: PATH="$(Pipeline.Workspace)/.cargo/bin:$PATH" ci/multinode_integration_test.sh
    displayName: "Run multinode integration tests"
